[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
target-version = ['py34']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env??
  | env
)/
'''
